import Link from 'next/link';

export const metadata = { title: 'Terms of Service — FomoForms' };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-2xl mx-auto px-5 py-12">
        <Link href="/" className="text-[#8e8e93] text-sm hover:text-[#1a1a1a] transition-colors">← Back</Link>

        <h1 className="text-3xl font-bold tracking-tight mt-6 mb-2">Terms of Service</h1>
        <p className="text-[#8e8e93] text-sm mb-8">Last updated: April 2026</p>

        <div className="space-y-6">
          <section>
            <h2 className="text-lg font-semibold mb-2">1. The service</h2>
            <p className="text-sm text-[#1a1a1a] leading-relaxed">
              FomoForms provides an AI-powered lead generation tool that creates personalised timeline calculators for coaches and service professionals. By creating an account, you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">2. Accounts</h2>
            <ul className="text-sm text-[#1a1a1a] space-y-1.5 list-disc pl-5">
              <li>You must provide accurate information when creating your account</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You are responsible for all content you add to your landing page</li>
              <li>You must not use the service for any unlawful purpose</li>
              <li>One account per person — do not share login credentials</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">3. Subscriptions and billing</h2>
            <ul className="text-sm text-[#1a1a1a] space-y-1.5 list-disc pl-5">
              <li>FomoForms is a paid subscription service billed monthly</li>
              <li>Payments are processed securely by Stripe</li>
              <li>Your subscription renews automatically each month</li>
              <li>You can cancel at any time from your Settings → Billing page</li>
              <li>Cancellation takes effect at the end of your current billing period</li>
              <li>We do not offer refunds for partial months</li>
              <li>We reserve the right to change pricing with 30 days notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">4. Referral programme</h2>
            <ul className="text-sm text-[#1a1a1a] space-y-1.5 list-disc pl-5">
              <li>Rewards are unlocked at each milestone: 1 referral (50% off next month), 2 (1 month free), 3 (2 months free), 4 (1 month Pro free), 5 (50% off for life — first 50 users)</li>
              <li>Referrals must be genuine new users with active paid subscriptions</li>
              <li>Self-referrals or fraudulent referrals will result in removal of all referral rewards</li>
              <li>The &ldquo;50% off for life&rdquo; tier is limited to the first 50 users who reach 5 referrals</li>
              <li>We reserve the right to modify or end the referral programme at any time</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">5. Your content</h2>
            <ul className="text-sm text-[#1a1a1a] space-y-1.5 list-disc pl-5">
              <li>You retain ownership of all content you upload (photos, logos, text)</li>
              <li>You grant us a licence to display your content as part of the service</li>
              <li>You must not upload content that is illegal, offensive, or infringes on others&apos; rights</li>
              <li>You are responsible for the accuracy of your pricing and service descriptions</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">6. Lead data</h2>
            <ul className="text-sm text-[#1a1a1a] space-y-1.5 list-disc pl-5">
              <li>You are the data controller for leads captured through your page</li>
              <li>You must comply with UK GDPR when handling prospect data</li>
              <li>You must respond to data deletion requests from prospects</li>
              <li>You must not use prospect data for purposes other than the service you offer</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">7. AI-generated content</h2>
            <ul className="text-sm text-[#1a1a1a] space-y-1.5 list-disc pl-5">
              <li>Timeline narratives are generated by AI (Anthropic Claude) and are estimates only</li>
              <li>AI-generated timelines should not be interpreted as guaranteed results</li>
              <li>You are responsible for reviewing AI-generated content on your page</li>
              <li>We are not liable for any inaccuracies in AI-generated content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">8. Availability</h2>
            <p className="text-sm text-[#1a1a1a] leading-relaxed">
              We aim to keep the service available 24/7 but do not guarantee uptime. We may perform maintenance that temporarily affects availability. We are not liable for any loss resulting from service interruptions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">9. Limitation of liability</h2>
            <p className="text-sm text-[#1a1a1a] leading-relaxed">
              FomoForms is provided &ldquo;as is&rdquo;. To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability is limited to the amount you have paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">10. Termination</h2>
            <ul className="text-sm text-[#1a1a1a] space-y-1.5 list-disc pl-5">
              <li>You can delete your account at any time from Settings → Billing</li>
              <li>We may terminate accounts that violate these terms</li>
              <li>On termination, your data will be deleted in accordance with our Privacy Policy</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">11. Changes to these terms</h2>
            <p className="text-sm text-[#1a1a1a] leading-relaxed">
              We may update these terms from time to time. We will notify you of significant changes via email. Continued use of the service after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">12. Governing law</h2>
            <p className="text-sm text-[#1a1a1a] leading-relaxed">
              These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">Contact</h2>
            <p className="text-sm text-[#1a1a1a] leading-relaxed">
              Questions about these terms? Contact us at{' '}
              <a href="mailto:hello@fomoforms.com" className="text-[#007AFF]">hello@fomoforms.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
